### ISSUE TITLE
SSL problems (due to StartCom?)

### ISSUE THREAD

**Issue by DanielGibson** [OpenTechEngine/modWiki#9]
On idtechforums *argoon* reported that his browsers (Chrome 57 and Vivaldi, which is also based on Chrome) will display an SSL error when trying to open https://modwiki.xnet.fi 
The error is `NET::ERR_CERT_AUTHORITY_INVALID`, see http://idtechforums.fuzzylogicinc.com/index.php?topic=539.0 for details.

This could be because the certificate is from StartCom which is generally not considered trustworthy anymore (see https://en.wikipedia.org/wiki/StartCom#Trustworthiness)

I guess it's time to switch to Let's Encrypt or something else

**Comment by DanielGibson** [comment]
@kortemik can you look into this? :)

**Comment by DanielGibson** [comment]
Google's blogpost explaining the situation https://security.googleblog.com/2016/10/distrusting-wosign-and-startcom.html

**Comment by kortemik** [comment]
letsencrypt in use now

**Comment by kortemik** [comment]
https://crt.sh/?id=142343454

**Comment by DanielGibson** [comment]
Awesome, thanks a lot!
